Document: phpvm
Title: Debian phpvm Manual
Author: <insert document author here>
Abstract: This manual describes what phpvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/phpvm/phpvm.sgml.gz

Format: postscript
Files: /usr/share/doc/phpvm/phpvm.ps.gz

Format: text
Files: /usr/share/doc/phpvm/phpvm.text.gz

Format: HTML
Index: /usr/share/doc/phpvm/html/index.html
Files: /usr/share/doc/phpvm/html/*.html
